name: Run Test

on:
  push:
    branches: 
      - "develop"
      - "master"
  pull_request:
    branches: 
      - "develop"
      - "master"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Xcode
      working-directory: WhatWeEat
      run: |
        xcodebuild test -project WhatWeEat/WhatWeEat.xcodeproj -scheme WhatWeEat -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=14.1'
