name: Run Test

on:
  push:
    branches: 
      - "develop"
  pull_request:
    branches: 
      - "develop"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run unit tests
      run: |
        xcodebuild clean test -project WhatWeEat.xcodeproj \
        -scheme WhatWeEat \
        -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest'
